-- insert into about(id, full_name, profile, email, phone, about_me, image) values
--              (1, 'Frimu Victor', 'Pictor', 'email', 'phone',
--               'about_me', '/resources/static/img/victor.jpg')
--
-- insert into gallery_item(id, date, image, title) values
--              (1, '20 noiembrie 2022', '/resources/static/img/tablouri/img.png', 'Tablou 1'),
--             (2, '20 noiembrie 2022', '/resources/static/img/tablouri/img_1.png', 'Tablou 2'),
--             (3, '20 noiembrie 2022', '/resources/static/img/tablouri/img_2.png', 'Tablou 3'),
--             (4, '20 noiembrie 2022', '/resources/static/img/tablouri/img_3.png', 'Tablou 4'),
--             (5, '20 noiembrie 2022', '/resources/static/img/tablouri/img_4.png', 'Tablou 5')